---
# EXAMPLE CONFIGURATION
#
# You will want to change these settings to values that are
# appropriate for your environment.

os_image: Fedora27
os_key_name: lars
os_flavor: m1.medium
os_networks:
  - nic_name: lars_network
os_security_groups:
  - default
  - webserver
os_public_network: public
docker_group: wheel
grafana_bind_address: 127.0.0.1
grafana_port: 3000
