- hosts: localhost
  tags:
    - openstack
  tasks:
    - name: provision a server
      os_server:
        state: present
        name: docker_host
        image: "{{ os_image }}"
        key_name: "{{ os_key_name }}"
        flavor: "{{ os_flavor }}"
        nics: "{{ os_networks }}"
        security_groups: "{{ os_security_groups }}"

    - name: acquire and assign a floating ip
      os_floating_ip:
        state: present
        server: docker_host
        network: "{{ os_public_network }}"
        wait: true

    - meta: refresh_inventory

# wait for target host to finish booting
- hosts: docker_host
  gather_facts: false
  tags:
    - openstack
  tasks:
    - wait_for_connection:

# install and start docker on the target host
- hosts: docker_host
  become: true
  tags:
    - docker
  roles:
    - docker

- hosts: docker_host
  tags:
    - docker
  tasks:
    - name: wait for docker to become active
      command: docker info
      changed_when: false
      register: docker_active
      until: docker_active.rc == 0
      retries: 60
      delay: 2

# start up grafana container under docker
- hosts: docker_host
  tags:
    - grafana
  roles:
    - grafana_container
