---
- name: create docker-compose project directory
  file:
    path: ./grafana
    state: directory

- name: create docker-compose.yml
  template:
    src: docker-compose.yml
    dest: ./grafana/docker-compose.yml
  register: compose

- name: create haproxy.cfg
  template:
    src: haproxy.cfg
    dest: ./grafana/haproxy.cfg
  register: haproxy_cfg

- name: install ssl certificate
  copy:
    src: "{{ ssl_cert_file }}"
    dest: ./grafana/server.crt
  when: haproxy_use_ssl

- name: shut down compose application
  command: docker-compose down
  args:
    chdir: ./grafana
  when: compose|changed or haproxy_cfg|changed

- name: start up compose application
  command: docker-compose up -d
  args:
    chdir: ./grafana
