version: "3"

services:
  grafana:
    image: "{{ grafana_image }}"
    volumes:
      - "grafana:/var/lib/grafana"
      - "./grafana:/etc/grafana"
    environment:
      GF_INSTALL_PLUGINS: "gnocchixyz-gnocchi-datasource"
      GF_SERVER_ROOT_URL: "http://{{ grafana_address }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
    restart: always

  haproxy:
    image: "{{ haproxy_image }}"
    volumes:
      - "./haproxy:/usr/local/etc/haproxy"
    ports:
{% if haproxy_use_ssl %}
      - "{{ haproxy_bind_address }}:{{ haproxy_https_port }}:443"
{% else %}
      - "{{ haproxy_bind_address }}:{{ haproxy_http_port }}:80"
{% endif %}
    restart: always

volumes:
  grafana:
