version: "3"

services:
  grafana:
    image: {{ grafana_image }}
    volumes:
      - "grafana:/var/lib/grafana"
    environment:
      GF_INSTALL_PLUGINS: "gnocchixyz-gnocchi-datasource"
      GF_SERVER_ROOT_URL: "http://{{ grafana_address }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
    ports:
      - "{{ grafana_bind_address }}:{{ grafana_port }}:3000"

volumes:
  grafana:
